apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: flask
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      annotations:
        rollme: {{ template "rollMe" . }}
      labels:
        app: flask
    spec:
      serviceAccountName: secret-backend-handler
      initContainers:
        {{- include "createDBInitContainer" . | nindent 8 }}
          - name: NEW_DB
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: PGDATABASE
        - name: db-migrations
          image: {{ template "backend-image" . }}
          command: ["/bin/sh"]
          workingDir: /
          {{- include "nonRootSC" . | nindent 10 }}
          args:
            [
              "-c",
              'python -m alembic upgrade head'
            ]
          envFrom:
            - configMapRef:
                name: backend-configmap
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Values.db.secret.name}}
                key: {{.Values.db.secret.key}}
        - name: storage-init
          image: {{ include "fn-alpine" . }}
          command: ["/bin/sh"]
          args:
            - -c
            - mkdir -p /mnt/storage/results
          volumeMounts:
            - name: respv
              mountPath: /mnt/storage
      containers:
        - image: {{ template "backend-image" . }}
          name: backend
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- include "nonRootSC" . | nindent 10 }}
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
          ports:
            - name: http
              containerPort: {{ .Values.federatedNode.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready_check
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health_check
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: backend-configmap
            - configMapRef:
                name: keycloak-config
          env:
          - name: RABBIT_HOST
            valueFrom:
              secretKeyRef:
                name: {{ index .Values "federated-node-slm" "rabbitmq" "existingPasswordSecret" }}
                key: username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ index .Values "federated-node-slm" "rabbitmq" "existingPasswordSecret" }}
                key: {{ index .Values "federated-node-slm" "rabbitmq" "existingPasswordSecretKey" }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Values.db.secret.name}}
                key: {{.Values.db.secret.key}}
          - name: KEYCLOAK_SECRET
            valueFrom:
              secretKeyRef:
                name: kc-secrets
                key: KEYCLOAK_GLOBAL_CLIENT_SECRET
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kc-secrets
                key: KEYCLOAK_ADMIN_PASSWORD
          volumeMounts:
            - name: respv
              mountPath: {{ .Values.federatedNode.volumes.results_path }}
              subPath: results
      volumes:
        - name: respv
          persistentVolumeClaim:
            claimName: {{ include "pvcName" . }}
