apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create"]
- apiGroups: ["", "batch"]
  resources: ["pods", "persistentvolumes", "persistentvolumeclaims", "jobs", "pods/exec"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-role
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: secret-backend-handler
roleRef:
  kind: ClusterRole
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-backend-handler
  namespace: {{ .Release.Namespace }}
