## This assumes for certain secrets to be present in the release namespace
# Basically duplicates them to the keycloak's namespace
{{- range list .Values.db.secret.name }}
{{ $sec := lookup "v1" "Secret" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}
  namespace: {{ include "kc_namespace" $ }}
data:
{{- with $sec.data }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $sec.type }}
---
{{- end }}
{{- if .Values.storage.azure }}
{{ $sec := lookup "v1" "Secret" .Release.Namespace .Values.storage.azure.secretName | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.azure.secretName }}
  namespace: {{ include "tasks_namespace" . }}
data:
{{- with $sec.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $sec.type}}
---
{{- end }}
{{- if and (index .Values "cert-manager" "enabled") (or .Values.on_eks .Values.on_aks) }}
{{ $sec := lookup "v1" "Secret" .Release.Namespace (.Values.certs.azure.secretName | default .Values.certs.aws) | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certs.azure.secretName }}
  namespace: {{ (index .Values "cert-manager" "namespace") }}
data:
{{- with $sec.data }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $sec.type }}
---
{{- end }}
{{- if .Values.storage.azure }}
{{ $sec := lookup "v1" "Secret" $.Release.Namespace .Values.storage.azure.secretName | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.azure.secretName }}
  namespace: {{ .Values.namespaces.tasks }}
data:
{{- with $sec.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $sec.type}}
---
{{- end }}
