{{ if .Values.create_db_deployment }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
spec:
  storageClassName: {{ .Release.Name }}-db-storage
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  # This should be changed to some more reliable destination
  {{ if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.dbpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  {{ else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  {{ else if .Values.storage.aws }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ include "awsStorageAccount" . }}
  {{ else if .Values.storage.nfs }}
  nfs:
    server: {{ .Values.storage.nfs.url }}
    path: {{ .Values.storage.nfs.path }}
    readOnly: false
  {{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volclaim
  namespace: {{ .Release.namespace }}
spec:
  storageClassName: {{ .Release.Name }}-db-storage
  # This should be changed to some more reliable destination
  volumeName: {{ .Release.Name }}-db-pv
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-db-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
volumeBindingMode: WaitForFirstConsumer
provisioner: Local
{{ end }}
