apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-init
  namespace: {{ .Values.namespaces.keycloak }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "3"
    {{ template "defaultAnnotations" . }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: "ghcr.io/aridhia-open-source/keycloak_initializer:{{ .Values.keycloak.tag | default .Chart.AppVersion }}"
          {{ include "nonRootSC" . }}
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_GLOBAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_GLOBAL_CLIENT_SECRET
          envFrom:
          - configMapRef:
              name: keycloak-config
