apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespaces.keycloak }}
  # Exception, so that init jobs can pick up the new port change.
  # Need to manually add the default annotations as well
  labels:
    {{ include "defaultLabels" . }}
  annotations:
    {{ include "defaultAnnotations" . }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-4"
    helm.sh/resource-policy: keep
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
