apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-credential-reset
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade,post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
    {{ template "defaultAnnotations" . }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      serviceAccountName: secret-backend-handler
      containers:
        - name: post-install-job
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: {{ include "fn-alpine" . }}
          command: ["keycloak-reset"]
          {{ include "nonRootSC" . }}
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Values.db.secret.name}}
                key: {{.Values.db.secret.key}}
          - name: KC_NAMESPACE
            value: {{ .Values.namespaces.keycloak }}
          - name: PGDATABASE
            value: {{ .Values.db.name | default "kc_db" }}
          envFrom:
          - configMapRef:
              name: backend-configmap
