{{- if index .Values "ingress-nginx" "enabled" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: federated-ingress
  labels:
    {{ include "defaultLabels" . }}
  annotations:
    {{ include "defaultAnnotations" . }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.whitelist.ips | quote }}
    {{- end }}
    {{- if .Values.blacklist.enabled }}
    nginx.ingress.kubernetes.io/denylist-source-range: {{ join "," .Values.blacklist.ips | quote }}
    {{- end }}
    helm.sh/hook: pre-install,pre-upgrade
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ index .Values "ingress-nginx" "controller" "ingressClass" }}
  tls:
  - hosts:
    - {{ .Values.host }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        - path: /(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: federated-ingress-keycloak
  namespace: {{ .Values.namespaces.keycloak }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.whitelist.ips | quote }}
    {{- end }}
    {{- if .Values.blacklist.enabled }}
    nginx.ingress.kubernetes.io/denylist-source-range: {{ join "," .Values.blacklist.ips | quote }}
    {{- end }}
    helm.sh/hook-weight: "5"
    rollme: {{ template "rollMe" . }}
spec:
  ingressClassName: {{ index .Values "ingress-nginx" "controller" "ingressClass" }}
  tls:
  - hosts:
    - {{ .Values.host }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
        - path: /keycloak/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: keycloak
              port:
                name: http
{{- end }}
