---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleaner-role
rules:
- apiGroups: ["", "batch"]
  resources: ["pods", "persistentvolumes", "persistentvolumeclaims", "jobs", "pods/exec"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleaner-role
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: task-cleaner-handler
roleRef:
  kind: ClusterRole
  name: cleaner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-cleaner-handler
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: result-cleaner
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          serviceAccountName: task-cleaner-handler
          containers:
          - name: result-cleaner
            image: {{ include "fn-alpine" . }}
            command: ["cleanup"]
            imagePullPolicy: {{ .Values.pullPolicy }}
            {{- include "nonRootSC" . | nindent 12 }}
            env:
            - name: NAMESPACE
              value: {{ .Values.namespaces.tasks }}
            - name: RESULTS_PATH
              value: {{ .Values.federatedNode.volumes.results_path }}
            - name: CLEANUP_AFTER_DAYS
              value: "{{ .Values.cleanupTime }}"
            volumeMounts:
            - name: respv
              mountPath: {{ .Values.federatedNode.volumes.results_path }}
              subPath: results
          restartPolicy: Never
          volumes:
          - name: respv
            persistentVolumeClaim:
              claimName: flask-results-pv-vc
