apiVersion: v1
kind: PersistentVolume
metadata:
  name: results-pv
spec:
  storageClassName: shared-results
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 100Mi
  # This should be changed to some more reliable destination
  {{ if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  {{ else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}/results
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  {{ else if .Values.storage.nfs }}
  {{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-results-pv-volclaim
  namespace: {{ .Release.namespace }}
spec:
  storageClassName: shared-results
  volumeName: results-pv
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadOnlyMany
