name: federated_node_ai_tests
services:
  db:
    ports:
      - 5432:5432
  keycloak:
    ports:
      - 8080:8080
  app:
    volumes:
      - ./tests:/app/tests
      - ./app:/app/app
      - ./setup.cfg:/app/setup.cfg
